[project]
name = "dataforge"
version = "0.1.0"
requires-python = "==3.12.13"
dependencies = [
    "requests==2.34.2",
    "psycopg==3.3.4",
    "duckdb==1.5.5"
]

[dependency-groups]
dev = [
    "flake8==7.3.0",
    "flake8-pyproject==1.2.4",
    "mypy==2.3.0",
    "pytest==9.1.1",
    "deptry==0.25.1",
]

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.flake8]
exclude = [
    ".venv",
    "venv",
    ".git",
    "__pycache__",
    "build",
    "dist",
]

[tool.deptry]
known_first_party = ["data_forge", "src"]
