name: Data Forge

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v7

      - name: Build
        run: just ci-up

      - name: Unit Test
        run: just ci-test

      - name: Clean up
        run: just ci-down